# Generated by Django 4.1.7 on 2023-02-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название')),
                ('name_in_english', models.CharField(max_length=55, verbose_name='Название (in english)')),
                ('active', models.BooleanField(default=False, verbose_name='Активный')),
                ('short_descr', models.CharField(max_length=155, verbose_name='Краткое описание')),
                ('detail_descr', models.TextField(verbose_name='Детальное описание')),
                ('short_descr_in_english', models.CharField(max_length=100, verbose_name='Краткое описание (in english)')),
                ('detail_descr_in_english', models.TextField(verbose_name='Детальное описание (in english)')),
                ('mo', models.CharField(max_length=255, verbose_name='МО')),
                ('subject_federation', models.CharField(max_length=100, verbose_name='Субъект федерации')),
                ('impact', models.CharField(max_length=155, verbose_name='Значимость')),
                ('locality', models.CharField(max_length=355, verbose_name='Населённый пункт')),
                ('locality_in_english', models.CharField(max_length=355, verbose_name='Населённый пункт (in english)')),
                ('address', models.CharField(max_length=155, verbose_name='Адрес')),
                ('address_in_english', models.CharField(max_length=155, verbose_name='Адрес')),
                ('oktmo', models.CharField(max_length=255, verbose_name='ОКТМО')),
                ('fcp', models.CharField(max_length=155, verbose_name='ФЦП (Федеральная целевая программа)')),
                ('move_with_object', models.CharField(max_length=255, verbose_name='Действия с объектом')),
                ('date_start_to_build', models.DateField(verbose_name='Дата начала строительства / реконструкции')),
                ('date_end_to_build', models.DateField(verbose_name='Дата завершения строительства / реконструкции')),
                ('financing', models.IntegerField(verbose_name='Общий объём финансирования')),
                ('financing_from_federal_budget', models.IntegerField(verbose_name='Финансирование из федерального бюджета')),
                ('financing_from_federal_budget_mastered', models.IntegerField(verbose_name='Финансирование из федерального бюджета (из них освоено)')),
                ('financing_from_subject_federal_budget', models.IntegerField(verbose_name='Финансирование из бюджета субъекта федерации')),
                ('financing_from_subject_federal_budget_mastered', models.IntegerField(verbose_name='Финансирование из бюджета субъекта федерации (из них освоено.)')),
                ('financing_from_mun_federal_budget', models.IntegerField(verbose_name='Финансирование из бюджета муниципального образования')),
                ('financing_from_mun_federal_budget_mastered', models.IntegerField(verbose_name='Финансирование из бюджета муниципального образования (из них освоено)')),
                ('financing_from_mne_budget_source', models.IntegerField(verbose_name='Финансирование из внебюджетных источников')),
                ('financing_from_mne_budget_source_mastered', models.IntegerField(verbose_name='Финансирование из внебюджетных источников (из них освоено)')),
                ('key_or_nope', models.BooleanField(default=False, verbose_name='Ключевой или нет?')),
                ('vising_organization', models.CharField(max_length=255, verbose_name='Курирующий орган')),
                ('vising_organization_in_english', models.CharField(max_length=255, verbose_name='Курирующий орган (in english)')),
                ('address_vising_organization', models.CharField(max_length=255, verbose_name='Адрес курирующего органа')),
                ('address_vising_organization_in_english', models.CharField(max_length=255, verbose_name='Адрес курирующего органа (in english)')),
                ('phone_number_organization', models.IntegerField(verbose_name='Телефон курирующего органа')),
                ('contact_number_object', models.IntegerField(verbose_name='Контактный телефон объекта')),
                ('job_mon_fri', models.CharField(max_length=255, verbose_name='Режим работы Пн.-Пт.')),
                ('job_sb', models.CharField(max_length=255, verbose_name='Режим работы Сб')),
                ('job_vs', models.CharField(max_length=255, verbose_name='Режим работы Вс')),
                ('square', models.IntegerField(verbose_name='Площадь')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('url_site', models.CharField(max_length=255, verbose_name='URL сайта')),
                ('reestr', models.BooleanField(default=False, verbose_name='Внесён в реестр?')),
                ('type_sport_complex', models.CharField(max_length=255, verbose_name='Тип спортивного комплекса')),
                ('compet_complex', models.TextField(verbose_name='Виды спорта')),
                ('cor_x_object', models.IntegerField(verbose_name='Яндекс координата объекта X')),
                ('cor_y_object', models.IntegerField(verbose_name='Яндекс координата объекта Y')),
                ('scale_yan_map', models.IntegerField(verbose_name='Маштаб Яндекс-карты')),
                ('cen_x', models.IntegerField(verbose_name='Яндекс координата центра X')),
                ('cen_y', models.IntegerField(verbose_name='Яндекс координата центра Y')),
                ('min_cor_x', models.IntegerField(verbose_name='Мини координата X')),
                ('min_cor_y', models.IntegerField(verbose_name='Мини координата Y')),
                ('general_plan', models.TextField(verbose_name='Дополнительные планы')),
                ('materials', models.CharField(max_length=255, verbose_name='Прочие материалы')),
            ],
        ),
    ]
