# Generated by Django 3.1.2 on 2023-03-02 14:33

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datas',
            options={'verbose_name': 'Данные от CSV файла', 'verbose_name_plural': 'Данные от CSV файла'},
        ),
        migrations.AddField(
            model_name='datas',
            name='dop_general_plan',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительные планы'),
        ),
        migrations.AddField(
            model_name='datas',
            name='type_sports',
            field=models.TextField(blank=True, null=True, verbose_name='Виды спорта'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='active',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='address',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='address_in_english',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='address_vising_organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес курирующего органа'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='address_vising_organization_in_english',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес курирующего органа (in english)'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='cen_x',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Яндекс координата центра X'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='cen_y',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Яндекс координата центра Y'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='compet_complex',
            field=models.TextField(blank=True, null=True, verbose_name='Какие соревнования проводятся?'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='contact_number_object',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Контактный телефон объекта'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='cor_x_object',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Яндекс координата объекта X'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='cor_y_object',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Яндекс координата объекта Y'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='date_end_to_build',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата завершения строительства / реконструкции'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='date_start_to_build',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата начала строительства / реконструкции'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='detail_descr',
            field=models.TextField(blank=True, null=True, verbose_name='Детальное описание'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='detail_descr_in_english',
            field=models.TextField(blank=True, null=True, verbose_name='Детальное описание (in english)'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='fcp',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='ФЦП (Федеральная целевая программа)'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='financing',
            field=models.FloatField(blank=True, null=True, verbose_name='Общий объём финансирования'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='financing_from_federal_budget',
            field=models.FloatField(blank=True, null=True, verbose_name='Финансирование из федерального бюджета'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='financing_from_federal_budget_mastered',
            field=models.FloatField(blank=True, null=True, verbose_name='Финансирование из федерального бюджета (из них освоено)'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='financing_from_mne_budget_source',
            field=models.FloatField(blank=True, null=True, verbose_name='Финансирование из внебюджетных источников'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='financing_from_mne_budget_source_mastered',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Финансирование из внебюджетных источников (из них освоено)'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='financing_from_mun_federal_budget',
            field=models.FloatField(blank=True, null=True, verbose_name='Финансирование из бюджета муниципального образования'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='financing_from_mun_federal_budget_mastered',
            field=models.FloatField(blank=True, null=True, verbose_name='Финансирование из бюджета муниципального образования (из них освоено)'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='financing_from_subject_federal_budget',
            field=models.FloatField(blank=True, null=True, verbose_name='Финансирование из бюджета субъекта федерации'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='financing_from_subject_federal_budget_mastered',
            field=models.FloatField(blank=True, null=True, verbose_name='Финансирование из бюджета субъекта федерации (из них освоено.)'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='general_plan',
            field=models.TextField(blank=True, null=True, verbose_name='Генеральный план'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='impact',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Значимость'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='job_mon_fri',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Режим работы Пн.-Пт.'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='job_sb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Режим работы Сб'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='job_vs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Режим работы Вс'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='key_or_nope',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевой или нет?'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='locality',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='Населённый пункт'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='locality_in_english',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='Населённый пункт (in english)'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='min_cor_x',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Мини координата X'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='min_cor_y',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Мини координата Y'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='mo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='МО'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='move_with_object',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Действия с объектом'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='name',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='name_in_english',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Название (in english)'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='oktmo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ОКТМО'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='phone_number_organization',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон курирующего органа'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='reestr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Внесён в реестр?'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='scale_yan_map',
            field=models.FloatField(blank=True, null=True, verbose_name='Маштаб Яндекс-карты'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='short_descr',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='short_descr_in_english',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Краткое описание (in english)'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='square',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='subject_federation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Субъект федерации'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='type_sport_complex',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип спортивного комплекса'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='url_site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL сайта'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='vising_organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Курирующий орган'),
        ),
        migrations.AlterField(
            model_name='datas',
            name='vising_organization_in_english',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Курирующий орган (in english)'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('patronymic', models.CharField(max_length=50, null=True, verbose_name='Фамилия')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
