# Generated by Django 3.1.2 on 2023-03-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230302_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=1, upload_to='users/', verbose_name='Аватарка'),
            preserve_default=False,
        ),
    ]
