# Generated by Django 3.1.2 on 2023-03-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230303_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactus',
            name='desc',
            field=models.TextField(max_length=175, verbose_name='Сообщение'),
        ),
    ]
